# Generated by Django 3.1.2 on 2021-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Football'), ('R', 'Running'), ('E', 'Excesising')], max_length=2),
        ),
    ]
